# Use an official Node.js runtime as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port your backend application runs on
EXPOSE 8080

# Start your backend application using 'node' with the main entry file (index.js)
CMD ["node", "index.js"]